config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  get "top/profile"
  resources :users
  post "/users/new" => "users#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    enum gender: { unknown: 0, male: 1, female: 2, other: 9 }
    
    #ユーザー名による絞り込み
    scope :get_by_name, ->(name) {
    where("name like ?", "%#{name}%")
    }
    
    #性別による絞り込み
    scope :get_by_gender, ->(gender) {
    where(gender: gender)
    }

    #性別による絞り込み
    scope :get_by_hometown, ->(hometown) {
    where(hometown: hometown)
    }
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
  def profile
    @user_name = "レイルズ"
    @gender = "man"
    @birthday = "1987/6/10"
    date_format = "%Y%m%d"
    birthday = @birthday.to_date
    @age = (Date.today.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10000
    @hometown = "愛知県"
    @skills = ["Ruby on Rails", "詩の朗読", "ものまね"]
    @remarks = "よろしくお願いします！"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    users = User.all
    if params[:name].present?
      users = users.get_by_name params[:name]
    end
    if params[:gender].present?
      users = users.get_by_gender params[:gender]
    end
    if params[:hometown].present?
      users = users.get_by_hometown params[:hometown]
    end
    @users = users.page(params[:page]).per(5)

  end
  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def create
    @user = User.new(users_params)
    if @user.save
      # 会員登録の場合は同時にログインしたいので下の1行が必要
      # session[:user_id] = @user.id
      flash[:notice] = "会員登録完了"
      redirect_to("/")
  else
      reder("users/new")
  end
  end
  def update
    @user = User.find(params[:id]) 
    @user.update_attributes(users_params)
    redirect_to @user
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def users_params
    params.require(:user).permit(:name, :gender, :birthday, :hometown, :remarks)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>レイアウトの編集</div>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<h1>Top#index</h1>
<p>Find me in app/views/top/index.html.erb</p>

app/views/top/profile.html.erb
<div class="profile">
    <h1>Top/profile</h1>
    <p>Find me in app/views/top/profile.html.erb</p>
    <%= image_tag 'noimage.png' %>
    <div>名前:  <%= @user_name %></div>
    <div>sex:  <%= @gender %></div>
    <div>誕生日:  <%= @birthday %></div>
     <% if @gender == "man" %>
    <div>年齢:  <%= @age %></div>
     <% end %>
    <div>出身:  <%= @hometown %></div>
    <% @skills.each do |skill| %>
    <div>特技:  <%= skill %></div>
    <% end %>
    <% if @remarks.present? %>
    <div>ひとこと:  <%= @remarks %></div>
    <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 <div>
  <%= f.text_field :name %>
  </div>
  <div>
  <%= f.select :gender, User.genders.keys %>
  </div>
  <div>
  <%= require "date"
      d = Date.today 
      last_year = d.year
      f.date_select :birthday, start_year: 1950, end_year: last_year %>
  </div>
  <div>
  <%= f.text_field :hometown %>
  </div>
  <div>
  <%= f.text_area :remarks %>
  </div>
  <div>
    <%= f.submit "送信する" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<div>
<%= form_tag(users_path, method: "get") do %>
<%= label_tag :name, "名前" %><%= text_field_tag :name, params[:name] %>
<%= label_tag :name, "性別" %>
<%= select_tag :gender, options_for_select(User.genders), include_blank: true %>
<%= label_tag :hometown, "出身地" %><%= text_field_tag :hometown, params[:hometown] %>
<%= submit_tag "検索" %>
<% end %>
</div>

<div>
  <%= link_to "ユーザーの新規登録", new_user_path %>
</div>

<table>
<thead>
<tr>
<th>名前</th>
<th>性別</th>
<th>誕生日</th>
<th>出身</th>
<th>ひとこと</th>
</tr>
</thead>
<tbody>
<% @users.each do |user| %>
<tr>
  <td><%= link_to user.name, user_path(user) %></td>
  <td><%= user.gender %></td>
  <td><%= user.birthday %></td>
  <td><%= user.hometown %></td>
  <td><%= user.remarks %></td>
  <td><%= link_to "編集", edit_user_path(user) %></td>
  <td><%= link_to "削除", user_path(user), :method => :delete %></td>
</tr>
</tbody>
<% end %>
</table>
<%= paginate @users %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

    <div>名前:  <%= @user.name %></div>
    <div>性別:  <%= @user.gender %></div>
    <div>誕生日:  <%= @user.birthday %></div>
    <div>出身地:  <%= @user.hometown %></div>
    <div>ひとこと:  <%= @user.remarks %></div>
   